# Generated by Django 3.2.8 on 2021-11-10 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.TextField(blank=True, max_length=200)),
                ('data_procedimento', models.DateField()),
                ('responsavel', models.TextField(choices=[('SECRETARIA_OBRAS_SERVICOS', 'Secretaria de Obras e Servicos'), ('ASSUNTOS_JURIDICOS', 'Assuntos Juridicos'), ('ADMINISTRACAO_FINANCAS', 'Administracao e Financas'), ('GABINETE_PREFEITO', 'Gabinete do Prefeito'), ('SECRETARIA_EDUCACAO_CULTURA', 'Secretaria de Educacao e Cultura'), ('SECRETARIA_SAUDE', 'Secretaria da Saude'), ('SECRETARIA_DESENVOLVIMENTO_SOCIAL', 'Secretaria de Desenvolvimento Social'), ('SECRETARIA_DESENVOLVIMENTO_URBANO', 'Secretaria de Desenvolvimento Urbano')], default=0, max_length=40)),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
