# Generated by Django 3.2.8 on 2021-10-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20211022_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id_endereco',
        ),
    ]
