# Generated by Django 3.2.8 on 2021-10-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_pessoa_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
    ]
