# Generated by Django 3.2.8 on 2021-11-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_remove_pessoa_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cel',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rua',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
