# Generated by Django 3.2.8 on 2021-11-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20211109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.TextField(choices=[('MUNICIPE', 'Municipe'), ('VEREADOR', 'Vereador')], default=0, max_length=15),
        ),
    ]
