# Generated by Django 3.2.8 on 2021-11-10 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vereador', models.TextField(choices=[('JOAO', 'Joao Silva'), ('JOSE', 'Jose'), ('CAETANO', 'Caetano Veloso'), ('MARCOS', 'Marcos Oliveira'), ('MELISSA', 'Melissa Santos'), ('MARTA', 'Marta Feliciano'), ('LAURA', 'Laura Helena'), ('CINTIA', 'Cintia Figueiredo')], default=0, max_length=15)),
                ('solicitacao', models.TextField(blank=True, max_length=200)),
                ('foto_solicitacao', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
